//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int request_id { get; set; }
        public string request_name { get; set; }
        public System.DateTime date_from { get; set; }
        public System.DateTime date_to { get; set; }
        public int user_id { get; set; }
        public Nullable<int> day { get; set; }
        public Nullable<int> hour { get; set; }
        public Nullable<int> day_in_month { get; set; }
        public int frequency_id { get; set; }
        public System.Guid file_id { get; set; }
        public Nullable<System.Guid> recording_id { get; set; }
        public bool is_relevant { get; set; }
    
        public virtual Frequency Frequency { get; set; }
        public virtual User User { get; set; }
    }
}
