//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Frequency
    {
        public Frequency()
        {
            this.FrequencyToRequest = new HashSet<FrequencyToRequest>();
        }
    
        public int frequencyId { get; set; }
        public string frequency1 { get; set; }
    
        public virtual ICollection<FrequencyToRequest> FrequencyToRequest { get; set; }
    }
}
