//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FrequencyDays
    {
        public int frequencyDaysId { get; set; }
        public Nullable<int> FrequencyToRequestId { get; set; }
        public Nullable<int> day { get; set; }
    
        public virtual FrequencyToRequest FrequencyToRequest { get; set; }
    }
}
