//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FrequencyToRequest
    {
        public FrequencyToRequest()
        {
            this.FrequencyDays = new HashSet<FrequencyDays>();
        }
    
        public int FrequencyToRequestId { get; set; }
        public Nullable<int> frequencyId { get; set; }
        public Nullable<int> requestId { get; set; }
        public Nullable<bool> isComper { get; set; }
    
        public virtual Frequency Frequency { get; set; }
        public virtual Request Request { get; set; }
        public virtual ICollection<FrequencyDays> FrequencyDays { get; set; }
    }
}
