//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajax.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TasksEntities : DbContext
    {
        public TasksEntities()
            : base("name=TasksEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Contents> Contents { get; set; }
        public DbSet<CreditCompeny> CreditCompeny { get; set; }
        public DbSet<Frequency> Frequency { get; set; }
        public DbSet<FrequencyToRequest> FrequencyToRequest { get; set; }
        public DbSet<Path> Path { get; set; }
        public DbSet<PaymentDetails> PaymentDetails { get; set; }
        public DbSet<Request> Request { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<FrequencyDays> FrequencyDays { get; set; }
    }
}
