//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajax.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class PaymentDetails
    {
        [Required(ErrorMessage = "not null able")]
        [RegularExpression("[0-9]*", ErrorMessage = "numbers only")]
        [StringLength(9, MinimumLength = 9, ErrorMessage = "9 numbers")]
        public string userId { get; set; }
        public Nullable<int> CreditCompenyId { get; set; }
        [Required(ErrorMessage = "not null able")]
        [RegularExpression("[a-zA-Zà-ú]*", ErrorMessage = "letters only")]
        public string ownerName { get; set; }
        [Required(ErrorMessage = "not null able")]
        [RegularExpression("[0-9]*", ErrorMessage = "numbers only")]
        public string numCredit { get; set; }
        [Required(ErrorMessage = "not null able")]
        public Nullable<System.DateTime> validDate { get; set; }
        [Required(ErrorMessage = "not null able")]
        [RegularExpression("[0-9]*", ErrorMessage = "numbers only")]
        public string cvc { get; set; }

        public virtual CreditCompeny CreditCompeny { get; set; }
        public virtual User User { get; set; }
    }
}
