//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public Request()
        {
            this.Contents = new HashSet<Contents>();
            this.FrequencyToRequest = new HashSet<FrequencyToRequest>();
            this.Path = new HashSet<Path>();
        }
    
        public int requestId { get; set; }
        public string userId { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual ICollection<Contents> Contents { get; set; }
        public virtual ICollection<FrequencyToRequest> FrequencyToRequest { get; set; }
        public virtual ICollection<Path> Path { get; set; }
        public virtual User User { get; set; }
    }
}
