//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajax.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class User
    {
        public User()
        {
            this.Request = new HashSet<Request>();
        }
        [Required(ErrorMessage = "not null able")]
        [RegularExpression("[0-9]*", ErrorMessage = "numbers only")]
        [StringLength(9,MinimumLength =9,ErrorMessage ="9 numbers")]
        public string userId { get; set; }
        [Required(ErrorMessage = "not null able")]
        [RegularExpression("[a-zA-Zà-ú]*", ErrorMessage = "letters only")]
        public string firstName { get; set; }
        [Required(ErrorMessage = "not null able")]
        public string password { get; set; }
        [Required(ErrorMessage = "not null able")]
        [RegularExpression("[a-zA-Zà-ú]*", ErrorMessage = "letters only")]
        public string lastName { get; set; }
        [Required(ErrorMessage = "not null able")]
        [RegularExpression("[0-9]*",ErrorMessage ="numbers only")]
        public string phone { get; set; }
        [Required(ErrorMessage = "not null able")]
        [RegularExpression(@"[a-zA-Z0-9]*@[a-zA-Z0-9]*.[a-zA-Z0-9]*",ErrorMessage ="not valid")]
        public string mail { get; set; }
    
        public virtual PaymentDetails PaymentDetails { get; set; }
        public virtual ICollection<Request> Request { get; set; }
    }
}
