USE [master]
GO

/****** Object:  Database [ON_TIME]    Script Date: 26/02/2019 11:58:41 ******/
CREATE DATABASE [ON_TIME]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ON_TIME', FILENAME = N'D:\SqlData\PUPILS_Data\ON_TIME.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ON_TIME_log', FILENAME = N'D:\SqlData\PUPILS_Data\ON_TIME_log.ldf' , SIZE = 1344KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ON_TIME] ADD FILEGROUP [MyFiles]
GO

ALTER DATABASE [ON_TIME] ADD FILEGROUP [temp]
GO

ALTER DATABASE [ON_TIME] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ON_TIME].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ON_TIME] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ON_TIME] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ON_TIME] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ON_TIME] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ON_TIME] SET ARITHABORT OFF 
GO

ALTER DATABASE [ON_TIME] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ON_TIME] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ON_TIME] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ON_TIME] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ON_TIME] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ON_TIME] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ON_TIME] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ON_TIME] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ON_TIME] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ON_TIME] SET  ENABLE_BROKER 
GO

ALTER DATABASE [ON_TIME] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ON_TIME] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ON_TIME] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ON_TIME] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ON_TIME] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ON_TIME] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ON_TIME] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ON_TIME] SET RECOVERY FULL 
GO

ALTER DATABASE [ON_TIME] SET  MULTI_USER 
GO

ALTER DATABASE [ON_TIME] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ON_TIME] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ON_TIME] SET FILESTREAM( NON_TRANSACTED_ACCESS = FULL, DIRECTORY_NAME = N'fs' ) 
GO

ALTER DATABASE [ON_TIME] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ON_TIME] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ON_TIME] SET  READ_WRITE 
GO


